sonar.projectKey=next-friday_eslint-plugin-friday
sonar.organization=next-friday

sonar.sources=packages/eslint-plugin-friday/src
sonar.tests=packages/eslint-plugin-friday/tests
sonar.test.inclusions=packages/eslint-plugin-friday/tests/**/*.test.ts

sonar.javascript.lcov.reportPaths=packages/eslint-plugin-friday/coverage/lcov.info
sonar.exclusions=**/dist/**,**/docs/**

sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
